[package]
name = "eileda"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37", features = [ "image" ] }
bitmaps = "3.2"
paste = "1.0"
markdown = "1.0.0-alpha.20"
bitflags = "2.5"
